dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
networks:
  kovan:
    weth_token: "0x5eca15b12d959dfcf9c71c59f8b467eb8c6efd0b"
    lending_pool_addresses_provider: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
  mainnet-fork:
    weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
